{
 "title": "Performance",
 "time": { "from": "2021-12-12T06:03:16.238Z", "to": "2021-12-12T09:59:35.829Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Per 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,5m),\n  avg(amount) AS \"amount\"\nFROM input\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,5m)"
    }
   ]
  },
  {
   "title": "Request Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1h),\n  avg(amount) AS \"amount\"\nFROM input\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,1h)"
    }
   ]
  },
  {
   "title": "RMSE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1m),\n  avg(rmse) AS \"rmse\"\nFROM performance\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,1m)"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1m),\n  avg(accuracy) AS \"accuracy\"\nFROM performance\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,1m)"
    }
   ]
  }
 ]
}